### ISSUE TITLE
Error when running example

### ISSUE THREAD

**Issue by lfernandez55** [jaredhanson/passport-local#71]
After installing the files into a folder, running "npm install"  and then running "node app.js" from the command line I get the following error:

C:\Users\lfernandez\Documents\folders\node\login>node app.js

C:\Users\lfernandez\Documents\folders\node\login\app.js:79
app.configure(function() {
    ^
TypeError: Object function (req, res, next) {
    app.handle(req, res, next);
  } has no method 'configure'
    at Object.<anonymous> (C:\Users\lfernandez\Documents\folders\node\login\app.
js:79:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by jaredhanson** [comment]
An up-to-date Express 4.x example can be found here: https://github.com/passport/express-4.x-local-example
