### ISSUE TITLE
Login example broken

### ISSUE THREAD

**Issue by animanathome** [jaredhanson/passport-local#90]
Hi there, 

I was trying to run the login example and ran into a couple of issues: 

app.configure(function() {
TypeError: Object function (req, res, next) {
    app.handle(req, res, next);
  } has no method 'configure'
    at Object.<anonymous> (/Users/manu/GitHub/passport-local/examples/login/app.js:79:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

and 

Error: Most middleware (like logger) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.
    at Function.Object.defineProperty.get (/Users/manu/node_modules/express/lib/express.js:89:13)
    at Object.<anonymous> (/Users/manu/GitHub/passport-local/examples/login/app.js:82:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

It looks like a couple of things have changed since the example was written. Do you think it would be possible to see it updated?

Thanks,

Manu

**Comment by GochoMugo** [comment]
Almost related to issue #71

**Comment by jaredhanson** [comment]
An up-to-date Express 4.x example can be found here: https://github.com/passport/express-4.x-local-example
